---
- name: Deploy a jar file
  hosts: all
  remote_user: root
  tasks:
    - name: Copy jar file to home directory
      copy:
        src: ./target/scientificCalculator-devops-1.0-SNAPSHOT.jar
        dest: ~/
        mode: '0755'